"""empty message

Revision ID: c87d59128bc1
Revises: None
Create Date: 2022-05-22 23:40:14.386722

"""

# revision identifiers, used by Alembic.
revision = 'c87d59128bc1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
